spring.application.name=usuarioev
server.port=8081

Eureka Client

eureka.client.service-url.defaultZone=https://eureka-server-pmc5.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true



# postgresql://neondb_owner:npg_NlLb9gci0VAf@ep-mute-math-aqujhxyw-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require


spring.datasource.url=jdbc:postgresql://ep-mute-math-aqujhxyw-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=

# Configuraci\u00f3n de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect